version: '2'

services:
  modem1:
    build: ./dnsmasq/.
    container_name: modem1
    hostname: modem1
    environment:
      - DNS_SERVER=8.8.8.8
      - LAN_IFACE=eth0
      - LAN_IP=192.168.1.1
      - LAN_RANGE_MIN=192.168.1.50
      - LAN_RANGE_MAX=192.168.1.100
    networks:
      lan:
        ipv4_address: 192.168.1.1
    cap_add:
      - NET_ADMIN
  modem2:
    build: ./dnsmasq/.
    container_name: modem2
    hostname: modem2
    environment:
      - DNS_SERVER=8.8.8.8
      - LAN_IFACE=eth0
      - LAN_IP=192.168.2.1
      - LAN_RANGE_MIN=192.168.2.50
      - LAN_RANGE_MAX=192.168.2.100
    networks:
      lan:
        ipv4_address: 192.168.2.1
    cap_add:
      - NET_ADMIN

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
          internal: true
